apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rundeck.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rundeck.name" . }}
    helm.sh/chart: {{ include "rundeck.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rundeck.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.annotations }}
      # Annotations iteration - Useful for KIAM and others
      annotations:
        {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "rundeck.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /bin/sh
          - -c
          - echo {{ .Values.rundeck.adminUser  }} > /home/rundeck/server/config/realm.properties && /home/rundeck/docker-lib/entry.sh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-environment-configmap
          volumeMounts:
          - name: data
            mountPath: /home/rundeck/server/data
        {{- if .Values.rundeck.sshSecrets }}
          - name: sshkeys
            mountPath: /home/rundeck/.ssh
            readOnly: true
        {{- end }}
        {{- if .Values.rundeck.awsCredentialsSecret }}
          - name: aws-credentials
            mountPath: /home/rundeck/.aws/credentials
        {{- end }}
        {{- if .Values.rundeck.customConfig }}
          - mountPath: /etc/remco/templates/rundeck-config.properties
            name: rundeck-config
            subPath: rundeck-config.properties
        {{- end }}
          ports:
            - name: rundeck
              containerPort: 4440
          livenessProbe:
            httpGet:
              path: /
              port: 4440
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: 4440
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaimLib | default (printf "%s-lib" ( include "rundeck.fullname" . )) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.rundeck.sshSecrets }}
        - name: sshkeys
          secret:
            secretName: {{ .Values.rundeck.sshSecrets }}
        {{- end }}
        {{- if .Values.rundeck.awsCredentialsSecret }}
        - name: aws-credentials
          secret:
            secretName: {{ .Values.rundeck.awsCredentialsSecret}}
        {{- end }}
        {{- if .Values.rundeck.custonConfig }}
        - configMap:
            defaultMode: 511
            name: {{ include "rundeck.fullname" . }}
          name: rundeck-config
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
